cal = read.csv("California.csv")
plot(cal$pop~cal$percover64)
m = lm(pop~percover64, data = cal)
summary(m)
boxcox(m)
boxcox(pop~percover64, data = cal)
m_log = lm(log(pop)~percover64, data = cal)
plot(log(cal$pop)~cal$percover64)
m_log2 = lm(log(pop)~log(percover64), data = cal)
summary(m_log2)
plot(m_log2$residuals~m_log2$fitted.values)
hist(m_log2$residuals)
qqnorm(m_log2$residuals)
shapiro.test(m_log2$residuals)
plot(log(cal$pop)~log(cal$percover64))
cor.test(log(cal$pop), log(cal$percover64))
library(MASS)
cal$logo64 = log(cal$percover64)
cal$logopop = log(cal$pop)
cal$sres=stdres(m_log2)
hist(cal$sres)
subset(cal,cal$sres< -3)

subset(cal,cal$sres > 3)
cal1=subset(cal,abs(cal$sres) < 3)
mo_log2 = lm(logopop~logo64, data = cal1)
summary(mo_log2)
plot(mo_log2$residuals~mo_log2$fitted.values)
hist(mo_log2$residuals)
qqnorm(mo_log2$residuals)
shapiro.test(mo_log2$residuals)
hist(cal1$sres)

newdata=data.frame(logo64=log(c(20,30,40,50,60,70)))
pred=predict(mo_log2,newdata,interval="prediction")
pred
pred = exp(pred)
pred

ce = read.csv("Cereals.csv")
fit = lm(Rating~Type+Calories+Protein+Sodium+Fiber+Carbo+Potass+Vitamins, data = ce)
summary(fit)
fit1 = lm(Rating~Calories+Protein+Sodium+Fiber+Carbo+Potass+Vitamins, data = ce)
fit_test = lm(Rating~Type+Calories+Protein+Sodium+Fiber+Carbo+Vitamins, data = ce)
ce$test = stdres(fit_test)
summary(fit_test)
plot(fit_test$res~fit_test$fitted.values)
summary(fit1)
ce$sres=stdres(fit1)
plot(fit$residuals~fit$fitted.values)
hist(fit_test$residuals)
qqnorm(fit$residuals)
shapiro.test(fit_test$residuals)

hist(ce$test)

hist(cal1$sres)
library(MASS)
ce$sres=stdres(fit)
fit$residuals
stdres(fit)

boxplot(ce$Rating~ce$Vitamins)
plot(ce$Rating~ce$Potass)
boxplot(ce$Rating~poly(ce$Manuf, 2))

library(boot)
set.seed(1)
plot(auto$mpg~auto$horsepower)
glm.fit= glm(Rating~Type+Calories+Protein+Sodium+Fiber+Carbo+Vitamins, data = ce)
cv.error = cv.glm(ce, glm.fit, )$delta[1]
cv.error
